# Generated by Django 3.0.3 on 2020-03-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_title', models.CharField(max_length=200)),
                ('tot_content', models.TextField()),
            ],
        ),
    ]
