# Generated by Django 3.0.3 on 2020-03-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2', '0002_tot_top_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_title', models.CharField(max_length=200)),
                ('tot_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
