# Generated by Django 3.0.3 on 2020-03-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2', '0003_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='tot_image',
            field=models.ImageField(upload_to='MEDIA_DIR'),
        ),
    ]
