# Generated by Django 3.0.3 on 2020-03-31 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2', '0005_auto_20200331_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='tot_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
