# Generated by Django 3.0.3 on 2020-07-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2', '0008_others'),
    ]

    operations = [
        migrations.RenameField(
            model_name='others',
            old_name='tot_image',
            new_name='tot_image1',
        ),
    ]
