# Generated by Django 3.0.3 on 2020-07-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2', '0009_auto_20200728_1434'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='others',
            new_name='work1',
        ),
    ]
