# Generated by Django 3.0.3 on 2020-07-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2', '0010_auto_20200728_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='tot_cat',
            field=models.CharField(choices=[('l', 'Living'), ('d', 'Dinnig'), ('b', 'Bedroom'), ('p', 'bathroom'), ('k', 'kitchen'), ('o', 'others')], default='o', max_length=1),
            preserve_default=False,
        ),
    ]
