# Generated by Django 3.0.3 on 2020-08-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2', '0011_work_tot_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='bd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bd_title', models.TextField()),
                ('bd_image', models.ImageField(upload_to='images/bedroom/')),
            ],
        ),
        migrations.CreateModel(
            name='bt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bt_title', models.TextField()),
                ('bt_image', models.ImageField(upload_to='images/bathroom/')),
            ],
        ),
        migrations.CreateModel(
            name='dinning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_title', models.TextField()),
                ('d_image', models.ImageField(upload_to='images/dinning/')),
            ],
        ),
        migrations.CreateModel(
            name='kitchen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_title', models.TextField()),
                ('k_image', models.ImageField(upload_to='images/kitchen/')),
            ],
        ),
        migrations.CreateModel(
            name='living',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_title', models.TextField()),
                ('l_image', models.ImageField(upload_to='images/living/')),
            ],
        ),
        migrations.CreateModel(
            name='o',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_title', models.TextField()),
                ('o_image', models.ImageField(upload_to='images/other/')),
            ],
        ),
        migrations.DeleteModel(
            name='work',
        ),
        migrations.DeleteModel(
            name='work1',
        ),
    ]
