# Generated by Django 3.0.3 on 2020-08-27 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p2', '0012_auto_20200801_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='p2.Post')),
            ],
        ),
        migrations.DeleteModel(
            name='bd',
        ),
        migrations.DeleteModel(
            name='bt',
        ),
        migrations.DeleteModel(
            name='dinning',
        ),
        migrations.DeleteModel(
            name='kitchen',
        ),
        migrations.DeleteModel(
            name='living',
        ),
        migrations.DeleteModel(
            name='o',
        ),
    ]
